//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_WithRepository.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponCodeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CouponCodeMaster()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int CouponId { get; set; }
        public string CouponCode { get; set; }
        public Nullable<int> CouponType { get; set; }
        public Nullable<int> CoupFlatAmount { get; set; }
        public Nullable<int> CouponPercentage { get; set; }
        public Nullable<System.DateTime> CouponExpiryDate { get; set; }
        public Nullable<int> CouponUsageLimit { get; set; }
        public Nullable<int> CouponIsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
